version: "3.8"

services:
    postgres:
        image: postgres:17
        container_name: bordados_postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: sistema_gestion_db
        ports:
            - "5433:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
